/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//this is mainly for PB11

int main(void)
{
	 uint32_t *pclocking = (uint32_t*) 0x40021018; // 0x4002 1000 +  0x18=0x40021018 RCC base address + Address offset. creating pointer registers
	 uint32_t *pmodechange =(uint32_t*) 0x40010C04 ;//0x4001 0C00 + 0x04 = 0x40010C04 GPIOB address + gpio mode register offset PAGE
     uint32_t *pDoutputset =(uint32_t*) 0x40010C0C ;// 0x4001 0C00 + 0x0C=0x40010C0C
     *pclocking |= ( 1 << 3); // CLOCK ENABLLLED
     *pmodechange &=~(15<<12) ;//masking with opposite of 15(1111) TO RESET IT
     *pmodechange |=(2<<12) ; //set to be (6<<20) PC13 OR (3<<21) NOW USING for PB11 shifting 2 on pin 12
    /* Loop forever */
	//for(;;);
   while(1)
     	{
     		//3.SET 13th bit of the output data register to make I/O pin-13 as HIGH
    	 	 *pDoutputset |= ( 1 << 11);

     		//introduce small human observable delay
     		//This loop executes for 200K times
     		for(uint32_t i=0 ; i < 200000 ; i++ );

     		//Tun OFF the LED
	   	   *pDoutputset &= ~( 1 << 11);


     		for(uint32_t i=0 ; i < 200000 ; i++ );
     	}
}





